// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBupXtTWKxoIpUSge5EdU-5dOriP-MoNUc',
    appId: '1:653607594609:web:cc34226a809abcddfe49d0',
    messagingSenderId: '653607594609',
    projectId: 'flutter-firebase-crud-4a45a',
    authDomain: 'flutter-firebase-crud-4a45a.firebaseapp.com',
    storageBucket: 'flutter-firebase-crud-4a45a.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD_6sRbFngwarkWVE2NeNsF13K7B56qv7I',
    appId: '1:653607594609:android:833364103cbf164efe49d0',
    messagingSenderId: '653607594609',
    projectId: 'flutter-firebase-crud-4a45a',
    storageBucket: 'flutter-firebase-crud-4a45a.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyADLV7Z3XayY_0sV_vWGjk06OeJtj1jo7M',
    appId: '1:653607594609:ios:beb604e3e5d90565fe49d0',
    messagingSenderId: '653607594609',
    projectId: 'flutter-firebase-crud-4a45a',
    storageBucket: 'flutter-firebase-crud-4a45a.appspot.com',
    iosClientId: '653607594609-moh2u2fdnukgj8png09hsenvp4a0cbml.apps.googleusercontent.com',
    iosBundleId: 'app.kleysonklaus.flutterFirebaseCrud',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyADLV7Z3XayY_0sV_vWGjk06OeJtj1jo7M',
    appId: '1:653607594609:ios:beb604e3e5d90565fe49d0',
    messagingSenderId: '653607594609',
    projectId: 'flutter-firebase-crud-4a45a',
    storageBucket: 'flutter-firebase-crud-4a45a.appspot.com',
    iosClientId: '653607594609-moh2u2fdnukgj8png09hsenvp4a0cbml.apps.googleusercontent.com',
    iosBundleId: 'app.kleysonklaus.flutterFirebaseCrud',
  );
}
